### ISSUE TITLE
HELP WANTED: Docker image of armhf for kodi-krypton-17.6

### ISSUE THREAD

**Issue by mr-honest** [linuxserver/docker-kodi-headless-armhf#17]
Hi @mammo0 and @sparklyballs or anyone else active in this docker image creations.
As I have media centers running MrMC on ATV4k (krypton DB, not yet updated to leia database) and kodi on standalones players (leia DB), I need to be able to download krypton version also in ARMHF. However I cannot download armhf version of krypton, when using "krypton" tag. This only works for the docker image for x86 kodi-headless.
Is it possible to download the image for kodi krypton 17.6 headless, via a tag?

Thank you both

**Comment by sparklyballs** [comment]
lsioarmhf/kodi-headless:38

will get you krypton

**Comment by mr-honest** [comment]
@sparklyballs 
Thank you very much sir.

Perhaps you can update the readme file for this valuable information?
